name: gensim
version: 0.0.3
homepage: https://github.com/relf108/gensim
description: A starting point for Dart libraries or applications.
environment: 
  sdk: '>=2.9.3 <3.0.0'
dependencies: 
  meta: ^1.2.3
dev_dependencies: 
  pedantic: ^1.9.0
  test: ^1.14.4
